import { BlogPost, Company } from "./types";

export const mockBlogs: BlogPost[] = Array.from({ length: 50 }, (_, i) => ({
  id: `blog-${i + 1}`,
  title: [
    "Building Scalable Microservices with Kubernetes",
    "The Future of Frontend Development: React vs. Vue",
    "Optimizing Database Performance in High-Load Applications",
    "Implementing CI/CD Pipelines for Faster Deployment",
    "How We Reduced Our API Response Time by 80%",
    "Machine Learning Models in Production: Lessons Learned",
    "The Evolution of Our Design System",
    "Serverless Architecture: Pros and Cons from Real-World Experience",
    "Build vs. Buy: How We Made the Decision",
    "Our Journey to GraphQL from REST",
  ][i % 10],
  excerpt: [
    "Learn how we built and scaled our microservices architecture using Kubernetes and Docker to handle millions of requests.",
    "An in-depth comparison of modern frontend frameworks and how we chose the right one for our needs.",
    "Practical tips and techniques for optimizing database performance in high-load applications.",
    "How we implemented continuous integration and deployment pipelines to ship code faster and more reliably.",
    "The technical journey of optimizing our API response times and the lessons we learned.",
  ][i % 5],
  content: "Full blog content would go here...",
  publishedAt: new Date(Date.now() - Math.floor(Math.random() * 30) * 24 * 60 * 60 * 1000).toISOString(),
  company: [
    "Google",
    "Microsoft",
    "Amazon",
    "Netflix",
    "Airbnb",
    "Stripe",
    "Vercel",
    "Meta",
    "Shopify",
    "Uber",
  ][i % 10],
  author: [
    "Sarah Johnson",
    "Michael Lee",
    "David Wilson",
    "Emily Chen",
    "James Rodriguez",
  ][i % 5],
  url: "https://example.com/blog",
  coverImage: [
    "https://images.pexels.com/photos/177598/pexels-photo-177598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/1181290/pexels-photo-1181290.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  ][i % 5],
  tags: [
    ["Kubernetes", "Microservices", "Docker", "DevOps"],
    ["React", "Vue", "JavaScript", "Frontend"],
    ["Database", "SQL", "Optimization", "Performance"],
    ["CI/CD", "DevOps", "Automation", "Testing"],
    ["API", "Performance", "Backend", "Optimization"],
    ["Machine Learning", "AI", "Data Science", "Production"],
    ["Design System", "UI", "UX", "Frontend"],
    ["Serverless", "AWS", "Cloud", "Architecture"],
    ["Decision Making", "Engineering", "Product", "Strategy"],
    ["GraphQL", "API", "REST", "Backend"],
  ][i % 10],
  readTime: Math.floor(Math.random() * 20) + 3,
}));

export const companies: Company[] = [
  { name: "Google", postCount: 243, lastUpdate: "2 days ago" },
  { name: "Microsoft", postCount: 187, lastUpdate: "1 day ago" },
  { name: "Amazon", postCount: 156, lastUpdate: "5 days ago" },
  { name: "Netflix", postCount: 132, lastUpdate: "3 days ago" },
  { name: "Airbnb", postCount: 98, lastUpdate: "1 week ago" },
  { name: "Stripe", postCount: 85, lastUpdate: "4 days ago" },
  { name: "Vercel", postCount: 76, lastUpdate: "Yesterday" },
  { name: "Meta", postCount: 203, lastUpdate: "3 days ago" },
  { name: "Shopify", postCount: 112, lastUpdate: "2 weeks ago" },
  { name: "Uber", postCount: 89, lastUpdate: "5 days ago" },
  { name: "Twitter", postCount: 167, lastUpdate: "4 days ago" },
  { name: "LinkedIn", postCount: 124, lastUpdate: "1 week ago" },
  { name: "Dropbox", postCount: 78, lastUpdate: "3 days ago" },
  { name: "Slack", postCount: 92, lastUpdate: "2 days ago" },
  { name: "Spotify", postCount: 83, lastUpdate: "Yesterday" },
];